# Generated by Django 3.0.5 on 2020-05-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=15)),
                ('UserType', models.CharField(max_length=15)),
                ('Surname', models.CharField(max_length=15)),
                ('Firstname', models.CharField(max_length=15)),
                ('Passcode', models.CharField(max_length=20)),
            ],
        ),
    ]
