# Generated by Django 3.0.5 on 2020-05-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200515_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='communicatingPartyId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parties', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='messageTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatId', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=3000)),
                ('sender', models.CharField(max_length=15)),
                ('receiver', models.CharField(max_length=15)),
                ('dateSent', models.DateTimeField()),
                ('status', models.CharField(max_length=10)),
                ('lastMessage', models.CharField(max_length=3)),
            ],
        ),
    ]
