from django.conf.urls import url
from  . import views
urlpatterns = [
    url(r'^login/$', views.Login, name= 'LoginPage'),
    url(r'^lecturer/upload/$', views.UploadResult, name= 'UploadResultPage'),
    url(r'^lecturer/pending/$', views.LecturerViewPending, name= 'PendingResultPage'),
    url(r'^lecturer/results/$', views.LecturerAllAcceptedResults, name= 'AllResultsPage'),
    url(r'^lecturer/allUsers/$', views.LecturerViewAllUsers, name='LecturerViewUsersPage'),
    url(r'^lecturer/user/(?P<userId>[\d]+)/$', views.LecturerViewUserDetails, name='LecturerViewProfilePage'),
    url(r'lecturer/chat/(?P<chatId>[\d]+)/$', views.LecturerChat, name='LecturerChatPage'),
    url(r'lecturer/Messages/$', views.LecturerAllMessages, name='LecturerMessagePage'),
    url(r'^lecturer/edit/(?P<ResultId>[\d]+)/$', views.LecturerEditResult, name= 'LecturerEditPage'),
    url(r'^lecturer/$', views.LecturerHomepage, name= 'LecturerHomepage'),
    url(r'^hod/selectResult/$', views.HodViewResultCategory, name='HodSelectResultCategoryPage'),
    url(r'^hod/result/$', views.HodViewResult, name='HodViewResultPage'),
    url(r'^hod/results/(?P<ResultId>[\d]+)/$', views.HodViewResultDetails, name= 'HodResultDetailsPage'),
    url(r'^hod/forward/(?P<ResultId>[\d]+)/$', views.HodForwardToExamOficer, name= 'HodForwardResultPage'),
    url(r'^hod/allUsers/$', views.HodViewAllUsers, name='HodViewUsersPage'),
    url(r'^hod/user/(?P<userId>[\d]+)/$', views.HodViewUserDetails, name='HodViewProfilePage'),
    url(r'hod/chat/(?P<chatId>[\d]+)/$', views.HodChat, name='HodChatPage'),
    url(r'hod/Messages/$', views.HodAllMessages, name='HodMessagePage'),
    url(r'^hod/$', views.HodHomepage, name='HodHomepage'),
    url(r'^ExamOfficer/selectResult/$', views.ExamOfficerViewResultCategory, name='ExamOfficerSelectResultCategoryPage'),
    url(r'^ExamOfficer/result/$', views.ExamOfficerViewResult, name='ExamOfficerViewResultPage'),
    url(r'^ExamOfficer/results/(?P<ResultId>[\d]+)/$', views.ExamOfficerViewResultDetails, name= 'ExamOfficerResultDetailsPage'),
    url(r'^ExamOfficer/viewCompile/(?P<ResultId>[\d]+)/$', views.ExamOfficerViewCompiledResult, name= 'ExamOfficerViewCompilePage'),
    url(r'^ExamOfficer/compile/(?P<ResultId>[\d]+)/$', views.ExamOfficerCompile, name= 'ExamOfficerCompilePage'),
    url(r'^ExamOfficer/allUsers/$', views.ExamOfficerViewAllUsers, name='ExamOfficerViewUsersPage'),
    url(r'^ExamOfficer/user/(?P<userId>[\d]+)/$', views.ExamOfficerViewUserDetails, name='ExamOfficerViewProfilePage'),
    url(r'ExamOfficer/chat/(?P<chatId>[\d]+)/$', views.ExamOfficerChat, name= 'ExamOfficerChatPage'),
    url(r'ExamOfficer/Messages/$', views.ExamOfficerAllMessages, name = 'ExamOfficerMessagePage'),
    url(r'^ExamOfficer/$', views.ExamOfficerHomepage, name='ExamOfficerHomepage'),

]